### ISSUE TITLE
Exports fails with Dependently typed type classes

### ISSUE THREAD

**Issue by wheaties** [milessabin/export-hook#10]
Attempting to Use `@imports[Foo]`, `@exports` and `@reexports` with type classes using dependent types fails. See the following. I believe they are all related.

``` scala
import export._

//contrived example

trait LF[A] extends DepFn[A]

@imports[LF]
object LF{
  //stuff
}

/*
[error] /Users/oreese/Workspace/playground/LF.scala:165: $tc has an unsupported kind
[error] @imports[LF]
[error]  ^
[error] /Users/oreese/Workspace/playground/LF.scala:165: trait LF takes type parameters
[error] @imports[LF]
[error]          ^
[error] two errors found
 */
```

**Comment by milessabin** [comment]
Were you planning to provide exports of some sort, somewhere else? If so, can you give a motivating example?

**Comment by milessabin** [comment]
I'd mainly like to know so that I can write a meaningful test :-)

**Comment by wheaties** [comment]
No problem. I'm trying to be able to abstract out a set of skeletal type classes around which I'll build an core lib. Then I can support both Scalaz and Cats without forcing the choice on another user. Hence,

``` scala
import foo.bar._
import foo.bar.Scalaz._  //and now derived type classes are based on Scalaz
```

Right now I have a hard-coded dependency on Scalaz.

**Comment by milessabin** [comment]
I'm having a tough time reproducing this. I had to adjust the example slightly because there's no such thing as plain `DepFn[T]` and because the `@imports` annotation has to be on a trait in the stack rather than on the topmost object (this is a limitation, but not obviously what's at issue here). The following compiles fine for me with the latest shapshot,

``` scala
import export._
import shapeless._

//contrived example

trait LF[A] extends DepFn1[A]

object LF extends LF0 {
  //stuff
}

@imports[LF]
trait LF0
```

It's possible that I fixed an issue that you were seeing in the last release ... can you try again with the latest snapshot?

**Comment by wheaties** [comment]
I created this repo: https://github.com/wheaties/export-hook-bug

Interestingly enough, if you disable wartremover, it compiles. If you add it in, you get the compiler problems.

**Comment by milessabin** [comment]
I get the following when I try and build that project,

```
[error] /home/miles/tmp/scala/export-hook-bug/next/src/main/scala/buz/algebird/AlgeThing.scala:8: AlgeStuff is already defined as object AlgeStuff
[error] object AlgeStuff
[error]        ^
[error] one error found
```

I'm happy to look into this, but I need a sensible starting point.

**Comment by wheaties** [comment]
The reexports bug is separate from wart remover. Should I open a new ticket? Also, sorry about not keeping that repo current to a bug.

**Comment by milessabin** [comment]
The following is a minimal reproduction of the type parameter bounds issue,

``` scala
import export._

@reexports[Foo] //uncomment for macro bug
object foo

trait Foo[A, B]

@exports
object Foo{
  implicit def fooInstance[A, B]: Foo[A, B] = ???
}
```

Yes, please do open a separate ticket for the wartremover interaction.
