### ISSUE TITLE
Type checking fails silently for re-exported type parameters

### ISSUE THREAD

**Issue by travisbrown** [milessabin/export-hook#12]
Just got caught by `reexports` not complaining when I forgot to fully qualify a type and gave it nonsense:

``` scala
@export.reexports[`This isn't a real type I've defined anywhere`]
object foo
```

[This line](https://github.com/milessabin/export-hook/blob/v1.0.2/core/src/main/scala/export/export.scala#L196) is the culprit, but I don't have enough context to know what changing `silent` to false would break.

**Comment by milessabin** [comment]
I should have checked before asking you to open this issue ... it's already fixed in the latest snapshot.

I'll close this with a test.

**Comment by milessabin** [comment]
Hmm ... unfortunately that doesn't seem to be straightforward because `illTyped` doesn't get on well with the type parameters on the `@reexport` annotation.

**Comment by milessabin** [comment]
Given that a test seems to be impossible I'll close anyway and hope for the best.
