### ISSUE TITLE
wartremover friendliness

### ISSUE THREAD

**Issue by fommil** [milessabin/export-hook#28]
(reminder to self... poke me if I don't do this)

I need to add these to my import/export objects

```
@SuppressWarnings(
  Array(
    "org.wartremover.warts.Null",
    "org.wartremover.warts.ExplicitImplicitTypes"
  )
)
```

I'm using `null` so it could be that the wartremover suppression annotation is not being copied in the macro, but the explicitimplicit warning looks like it's coming out of generated code.

to be investigated with post-typer dumps...

**Comment by milessabin** [comment]
The `null` is in your code. My hunch is that the missing annotation is also in your code. If you modify your method so that it has an explicit return type and implement as `???` then I think wart remover will be quiet.

**Comment by fommil** [comment]
Yes I have a `null` for the `cnil` case. Maybe I should return something else just to workaround this but it's a fairly common pattern I use.

nah, I definitely have the annotation. My implicits also have explicit return values (I'm asserting on both of these warts with fatal warnings). This could all be moot when wartremover ignores expanded macros.

**Comment by fommil** [comment]
`null` is not coming from the user code, it's being generated by the macro somewhere.

**Comment by milessabin** [comment]
Do you have a small, self-contained reproduction of this? Is so, please include or link to it in this ticket.

**Comment by milessabin** [comment]
I'm closing this for now. If you can come up with a minimal reproduction feel free to reopen.

**Comment by fommil** [comment]
I gave you a minimal reproduction in the linked PR showing that the bad generated code is *already the case*, I do not need to provide any additional examples. All macro generated code is inserting `null` and not adding explicit types to implicit `val`s. The former is forgivable in some cases, but the latter is bad style, with or without wartremover.

**Comment by fommil** [comment]
(btw, I'll never remember to do this if the ticket is closed. It won't show up in my custom github searches.)
